global:
  checkNewVersion: false
  sendAnonymousUsage: false
api:
  dashboard: true
  insecure: true

log:
  level: INFO
  format: json

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /traefik/var

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: https
          scheme: https
          
  https:
    address: ":443"

serversTransport:
  insecureSkipVerify: true