name: cron-update v2

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  cron-update:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: write

    steps:
      - name: cron-update / get latest version
        run: |
          VERSION="null"
          for PAGE in {0..10}; do
            VERSION=$(curl -s https://api.github.com/repos/traefik/traefik/tags?page=${PAGE} | jq -r ['.[].name | select(test("^v2")) '][0] | sed 's/v//')
            if [ "${VERSION}" != "null" ]; then
              break
            fi
          done
          echo "LATEST_VERSION_V2=${VERSION}" >> "${GITHUB_ENV}"

      - name: cron-update / build docker image
        if: env.LATEST_VERSION_V2 != 'null'
        uses: the-actions-org/workflow-dispatch@3133c5d135c7dbe4be4f9793872b6ef331b53bc7
        with:
          workflow: version.yml
          wait-for-completion: false
          token: "${{ secrets.REPOSITORY_TOKEN }}"
          inputs: '{ "version":"${{ env.LATEST_VERSION_V2 }}" }'